[paths]
video =  "../data/experiments/"
contours = "../data/contours"
midpoints = "../data/midpoints"
depca = "../data/DE-PCAs"
depca_individual = "../data/individual-DE-PCAs"
depca_bs = "../data/DE-PCAs/bootstraps"
area = "../data/"
stages = "../data/"