name = "ElegansTimeSeries"
uuid = "f1a013e0-8345-4c38-af95-892ebbb2582e"
authors = ["yha <yharel@campus.technion.ac.il>"]
version = "0.1.0"

[deps]
AlignedBinaryFormat = "94fc9360-1a5e-4d84-93be-ddbadb32b3a7"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Elegans = "27ab0b70-9e64-11e9-288f-a5d350afe8a8"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
ManifoldLearning = "06eb3307-b2af-5a2a-abea-d33192699d32"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
OptimalTransport = "7e02d93a-ae51-4f58-b602-d97af76e3b33"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
RLEVectors = "17b45ede-fd0d-54ef-b825-8cf9fc64da95"
RunningQuantiles = "80c66bcf-cf80-4640-8128-20a4ffc975e3"
SortFilters = "d6dedbf8-78c7-4e81-bd5f-fe48695b798a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unzip = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"
