name = "ElegansTimeSeries"
uuid = "f1a013e0-8345-4c38-af95-892ebbb2582e"
authors = ["yha <yharel@campus.technion.ac.il>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unzip = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"
