[deps]
AlignedBinaryFormat = "94fc9360-1a5e-4d84-93be-ddbadb32b3a7"
AverageShiftedHistograms = "77b51b56-6f8f-5c3a-9cb4-d71f9594ea6e"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Elegans = "27ab0b70-9e64-11e9-288f-a5d350afe8a8"
ElegansTimeSeries = "f1a013e0-8345-4c38-af95-892ebbb2582e"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
ManifoldLearning = "06eb3307-b2af-5a2a-abea-d33192699d32"
MarkdownLiteral = "736d6165-7244-6769-4267-6b50796e6954"
MosaicViews = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OptimalTransport = "7e02d93a-ae51-4f58-b602-d97af76e3b33"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProfileCanvas = "efd6af41-a80b-495e-886c-e51b0c7d77a3"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
RLEVectors = "17b45ede-fd0d-54ef-b825-8cf9fc64da95"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecipesPipeline = "01d81517-befc-4cb6-b9ec-a95719d0359c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TSne = "24678dba-d5e9-5843-a4c6-250288b04835"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"
Unzip = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"

[compat]
AlignedBinaryFormat = "~0.6.2"
AverageShiftedHistograms = "~0.8.8"
BlockArrays = "~0.16.20"
CSV = "~0.10.4"
CSVFiles = "~1.0.2"
DataFrames = "~1.3.4"
DataStructures = "~0.18.13"
Distances = "~0.10.7"
Distributions = "~0.25.70"
ElegansTimeSeries = "~0.1.0"
FileIO = "~1.15.0"
GLM = "~1.8.0"
GeometryBasics = "~0.4.3"
HypertextLiteral = "~0.9.4"
HypothesisTests = "~0.10.10"
ImageFiltering = "~0.7.2"
IterTools = "~1.4.0"
JLD2 = "~0.4.22"
JuliennedArrays = "~0.4.0"
LazyArrays = "~0.22.11"
MAT = "~0.10.3"
MarkdownLiteral = "~0.1.1"
MultivariateStats = "~0.9.0"
NaNMath = "~1.0.1"
NamedArrays = "~0.9.6"
OffsetArrays = "~1.12.7"
OptimalTransport = "~0.3.19"
PaddedViews = "~0.5.11"
PlotUtils = "~1.3.0"
PlutoUI = "~0.7.40"
PrettyTables = "~1.3.1"
ProfileCanvas = "~0.1.4"
ProgressLogging = "~0.1.4"
RLEVectors = "~0.9.7"
Revise = "~3.4.0"
StatsBase = "~0.33.21"
StatsPlots = "~0.15.2"
TSne = "~1.3.0"
Tulip = "~0.9.4"
Unzip = "~0.2.0"
